// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'features/user/models/user_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6220704968165888936),
    name: 'UserEntity',
    lastPropertyId: const obx_int.IdUid(11, 4528913415260542182),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7744294349020649539),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4818724453998566101),
        name: 'supabaseId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 3612423498336717838),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6421831188813422894),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8362249222820323208),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8000845306530632839),
        name: 'password',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9095729397813142953),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8491741601035799420),
        name: 'profilePicture',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7682034712220410954),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8424523755783333744),
        name: 'bio',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3547328222854294971),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4528913415260542182),
        name: 'updatedAt',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 6220704968165888936),
    lastIndexId: const obx_int.IdUid(1, 3612423498336717838),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    UserEntity: obx_int.EntityDefinition<UserEntity>(
      model: _entities[0],
      toOneRelations: (UserEntity object) => [],
      toManyRelations: (UserEntity object) => {},
      getId: (UserEntity object) => object.id,
      setId: (UserEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserEntity object, fb.Builder fbb) {
        final supabaseIdOffset = fbb.writeString(object.supabaseId);
        final nameOffset = fbb.writeString(object.name);
        final emailOffset = fbb.writeString(object.email);
        final passwordOffset = fbb.writeString(object.password);
        final roleOffset = fbb.writeString(object.role);
        final profilePictureOffset = fbb.writeString(object.profilePicture);
        final phoneNumberOffset = fbb.writeString(object.phoneNumber);
        final bioOffset = fbb.writeString(object.bio);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, supabaseIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, emailOffset);
        fbb.addOffset(4, passwordOffset);
        fbb.addOffset(5, roleOffset);
        fbb.addOffset(6, profilePictureOffset);
        fbb.addOffset(7, phoneNumberOffset);
        fbb.addOffset(8, bioOffset);
        fbb.addInt64(9, object.createdAt);
        fbb.addInt64(10, object.updatedAt);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final supabaseIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final passwordParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final profilePictureParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final bioParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final createdAtParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final updatedAtParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final object = UserEntity(
          id: idParam,
          supabaseId: supabaseIdParam,
          name: nameParam,
          email: emailParam,
          password: passwordParam,
          role: roleParam,
          profilePicture: profilePictureParam,
          phoneNumber: phoneNumberParam,
          bio: bioParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [UserEntity] entity fields to define ObjectBox queries.
class UserEntity_ {
  /// See [UserEntity.id].
  static final id = obx.QueryIntegerProperty<UserEntity>(
    _entities[0].properties[0],
  );

  /// See [UserEntity.supabaseId].
  static final supabaseId = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[1],
  );

  /// See [UserEntity.name].
  static final name = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[2],
  );

  /// See [UserEntity.email].
  static final email = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[3],
  );

  /// See [UserEntity.password].
  static final password = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[4],
  );

  /// See [UserEntity.role].
  static final role = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[5],
  );

  /// See [UserEntity.profilePicture].
  static final profilePicture = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[6],
  );

  /// See [UserEntity.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[7],
  );

  /// See [UserEntity.bio].
  static final bio = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[8],
  );

  /// See [UserEntity.createdAt].
  static final createdAt = obx.QueryIntegerProperty<UserEntity>(
    _entities[0].properties[9],
  );

  /// See [UserEntity.updatedAt].
  static final updatedAt = obx.QueryIntegerProperty<UserEntity>(
    _entities[0].properties[10],
  );
}
